# Generated by Django 3.2.8 on 2021-11-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_birth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
