# Generated by Django 3.2.8 on 2021-11-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='float',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_img_url',
            new_name='thumbnail_image_url',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
