# Generated by Django 3.2.8 on 2021-11-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211103_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_description1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_description2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='head_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
