# Generated by Django 3.2.9 on 2021-11-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Sub_category',
        ),
    ]
