# Generated by Django 3.2.9 on 2021-11-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_subcategory_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_category',
            new_name='Subcategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
